
#define VERBOSE_DEBUG_DEFAULT
//#define VERBOSE_DEBUG_VAR
//#define VERBOSE_DEBUG_RX
#define VERBOSE_DEBUG_DISTANCE_1
#define VERBOSE_DEBUG_DISTANCE_2
#define VERBOSE_DEBUG_TANK
#define VERBOSE_DEBUG_TANK_STATE    

#define DEFAULT_TANK_HEIGHT       1000
#define DEFAULT_TANK_FULL         700
#define DEFAULT_TANK_EMPTY        600

#define LCD_1602
#define LCD_NOKIA5110
